version: "3.8"

services:
  frontend:
    build: .
    container_name: almoxarifado-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules